config/routes.rb
require 'resque'
require 'resque-retry'
require 'resque-retry/server'

MediaAnalysis::Application.routes.draw do

  resources :shares

  match '/semantria/webhook', to: 'welcome#semantria', via: 'post'
  
  match '/api/users/authorizations', to: 'authorizations#user_list', via: 'get'
  
  ### Articles controller 
  match '/articles/topics', to: 'articles#topics', via: 'get'
  match '/articles/add_to_pocket', to: 'articles#add_to_pocket', via: 'post'


  ## ReadingLogs controller 
  match '/reading_logs/new', to: 'reading_logs#create', via:'post'
  match '/reading_logs/favorite', to: 'reading_logs#add_to_favorites', via: 'post'
  match '/reading_logs/hidden', to: 'reading_logs#mark_hidden', via: 'post'
  match '/reading_logs/:id', to: 'reading_logs#update', via: 'put'
  

  #Rails routes that generate views  
  devise_for :users,
      :controllers => {
        :omniauth_callbacks => "users/omniauth_callbacks",
        :registrations => "users/registrations",
        :sessions => "users/sessions"
      }
  authenticated :user do
    root :to => "welcome#dashboard", :as => "authenticated_root" 
  end
  
  root to: 'welcome#index'

  # match '/about', to: 'welcome#about',     via: 'get'
  # match '/privacy', to: 'welcome#privacy',     via: 'get'
  # match '/terms', to: 'welcome#terms',     via: 'get'
  match '/faqs', to: 'welcome#faqs', via: 'get'
  match '/deleted_account', to: 'welcome#goodbye', via:'get', as: 'deleted_account' 
  match '/chrome_extension_installed', to: "welcome#chrome_extension_installed", via: 'get'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :admin do 
    mount Resque::Server, :at => "/resque", as: 'resque'
  end
  
  ## Third party Authorization API calls
  match '/users/auth/pocket', to: 'authorizations#pocket_auth', via: 'get'
  match '/authorizations/pocket_middle', to: 'authorizations#pocket_middle', via: 'get'
  match '/users/auth/readability', to: 'authorizations#readability_auth', via: 'get'
  match '/authorizations/readability_middle', to: 'authorizations#readability_middle', via: 'get'
  match '/users/auth/feedly', to: 'authorizations#feedly_auth', via: 'get'
  match '/authorizations/feedly/callback', to: 'authorizations#feedly_callback', via: 'get'
  match '/authorizations/deauthorize/:provider', to: 'authorizations#deauthorize', via: 'delete'
  match '/users/auth/instapaper', to: "authorizations#instapaper_login", via: 'get'
  match '/users/auth/instapaper', to: "authorizations#instapaper_authorization", via: 'post'


  devise_scope :user do 
    get '/api/current_user' => 'users/sessions#show_current_user', as: 'show_current_user'
    get '/extension_login' => 'users/users#extension_login', as: 'extension_login'
    post '/api/check/is_user' => 'users/users#is_user', as: 'is_user'
    match '/users/:id', to: 'users/users#show', via: 'get'
    match '/users/:id/articles', to: 'users/users#user_articles', via: 'get'
    match '/api/users/discover', to: 'users/users#discover', via: 'get'
    match '/api/users/summary/:id', to: 'users/users#summary', via: 'get'
    match '/api/users/stats/:id', to: 'users/users#stats', via: 'get'
    match '/api/users/data_update_status', to: 'users/users#data_update_status', via: 'get'
    match '/api/users/common_articles/:id', to: 'users/users#common_articles', via: 'get'
    match '/users', to: 'users/users#index', via: 'get', as: 'users'
    match '/email_registration', to: 'users/registrations#ask_for_email', via: 'get', as: 'ask_for_email'
    match '/add_email', to: 'users/registrations#add_email', via: 'patch', as: 'add_email'
  end

  get '*path' => redirect('/')

end

app/views/layouts/_footer.html.erb
<div id="footer">
      <div class="container">
		<p class="text-muted credit"><!--  <%#= link_to("Privacy", privacy_path)%> &middot; <%#= link_to("Terms of Use", terms_path)%> &middot; --> <%= link_to("Blog", "http://blog.roundview.co/") %> <span class="pull-right">&copy; <%= Time.now.year%> Roundview</span></p>
      </div>
</div>

app/views/layouts/_nav_bar_signed_in.html.erb
    <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top" role="navigation" data-ng-controller="NavBarController">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
             
            <a ui-sref="profile.summary({userId: current_user.id, timePeriod: 12})">  
              <img src="https://s3.amazonaws.com/roundview4/static_assets/Roundview_logo_full.svg" alt="Roundview Logo" class="navbar-logo"> 
            </a>
             
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
               <li> <a ui-sref="profile.summary({userId: current_user.id, timePeriod: 12})"> My Profile </a></li>
               <li> <a ui-sref="discover"> Discover </a> </li>
               <li> <a ui-sref="connect_accounts"> Connect APIs </a></li> 
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li> <%= mail_to "contact@roundview.co", "Contact Us", :target => '_blank' %> </li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
            </ul>
            
            
          </div><!--/.nav-collapse -->
        </div>
      </div>  

app/views/layouts/_nav_bar_signed_out.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(root_path) do %>
             <img src="https://s3.amazonaws.com/roundview4/static_assets/Roundview_logo_full.svg" alt="Roundview Logo" class="navbar-logo">
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to("Home", root_path) %></li>
            <li><%= link_to("Blog", "http://blog.roundview.co/") %> </li>
            <li><%= link_to("FAQs", faqs_path) %></li>
            <li> <%= mail_to "contact@roundview.co", "Contact Us", :target => '_blank' %> </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if request.env['PATH_INFO'] != '/users/sign_up'%> 
              <li><%=link_to("Sign Up", new_user_registration_path, method: "get") %></li>
            <% end %> 
            <% if request.env['PATH_INFO'] == '/users/sign_up'%> 
              <li><%=link_to("Sign In", new_user_session_path, method: "get")%> </li>
            <% end %>
            <% if request.env['PATH_INFO'] == '/' || request.env['PATH_INFO'] == '/about' || request.env['PATH_INFO'] == '/alpha'%>
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
              <div class="dropdown-menu" id="sign-in-dropdown">
                <center> <a href="/users/auth/facebook"> <img src="https://s3.amazonaws.com/roundview4/images/facebook-login-button.png"></a></center>
                <br/>
                <h4 class="text-center">OR</h4>
                  <%= form_tag(user_session_path, class: "form") do%>
                      <div class="form-group">
                        <%= label_tag :email %>
                        <%= email_field(:user, :email, class: "form-control", placeholder: "Email") %>
                      </div>
                      <div class="form-group">
                        <%= label_tag :password %>
                        <%= password_field(:user, :password, class: "form-control", placeholder: "Password") %>
                      </div>
                      <div class="form-group">
                        <%= label_tag :remember_me %> 
                        <%= check_box(:user, :remember_me, class: "checkbox") %> 
                      </div>
                      <%= submit_tag "Sign in" , class: "btn btn-success" %>
                      
                  <%end %>
                <p class="help-block"> <%= link_to("Forgot password?", new_user_password_path) %> </p>
                <br/>
                
              </div>
              
            </li>
            <%end %>
            <!-- / li .dropdown -->
          </ul>
          
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/_public_footer.html.erb
<div id="footer">
      <div class="container">
		<p class="text-muted credit"><!--  <%#= link_to("Privacy", privacy_path)%> &middot; <%#= link_to("Terms of Use", terms_path)%> &middot; --> <%= link_to("Blog", "http://blog.roundview.co/") %>  <span class="pull-right"><a href="https://mixpanel.com/f/partner"><img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a> &copy; <%= Time.now.year%> Roundview</span></p>

      </div>
</div>

app/views/layouts/_shim.html.erb
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html lang="en" data-ng-app="mediaAnalysis">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="https://s3.amazonaws.com/roundview4/static_assets/roundview_logo_16.png"/>  
		<title><%= content_for?(:title) ? yield(:title) : "Roundview Beta" %></title>
		<meta name="description" content="Reading, Quantified Self, Reading Profile, Data, Statistics, Stats">
    	<meta name="author" content="Roundview">
		<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/baoichngodjibhnbdghdkhbjcmhkmfdc">
		<script type="text/javascript">
	      window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["identify","track"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
	      heap.load("1162175837");
	    </script>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag "application", :media => "all" %>
	</head>

	<body>
		<%= render 'layouts/nav_bar_signed_in' %> 
		<div class="container">
			<div ui-view></div>
		</div> <!-- /container -->
		<%= javascript_include_tag "application" %>
	</body>
	<%= render 'layouts/footer' %>
	<script>
		if (document.location.hostname.search("roundview.co") !== -1) {
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-46327528-2', 'auto');
		  ga('require', 'displayfeatures');
		}
	</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<%= stylesheet_link_tag    "application", media: "all" %>
  
  	<%= csrf_meta_tags %>
  	<%= render 'layouts/shim' %>
    <meta name="google-site-verification" content="MOYPrPABXhpxSq6X_K0X7QQpXsFFR1o2R44uvszddM8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Reading, Quantified Self, Reading Profile, Data, Statistics, Stats">
    <meta name="author" content="Roundview">
    <link rel="shortcut icon" href="https://s3.amazonaws.com/roundview4/static_assets/roundview_logo_16.png"/>  
    <link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/baoichngodjibhnbdghdkhbjcmhkmfdc">
    <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["identify","track"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("1162175837");
    </script>
    <title>Roundview: Your Online Reading Profile</title>
  </head>

  <body>

    <%= render 'layouts/nav_bar_signed_out' %>   
	
    <!-- Begin page content -->
    
    
    <%= yield %>
    

    
    
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
  <%= render 'layouts/public_footer' %>
  
  <script>
    if (document.location.hostname.search("roundview.co") !== -1) {
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-46327528-2', 'auto');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
    }
  </script>
</html>

app/views/layouts/authenticated.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<%= stylesheet_link_tag    "application", media: "all" %>
  
  	<%= csrf_meta_tags %>
  	<%= render 'layouts/shim' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Reading, Quantified Self, Reading Profile, Data, Statistics, Stats">
    <meta name="author" content="Roundview">
    <link rel="shortcut icon" href="https://s3.amazonaws.com/roundview4/static_assets/roundview_logo_16.png"/>  
    <link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/baoichngodjibhnbdghdkhbjcmhkmfdc">
    <title>Roundview Beta</title>
    <script type="text/javascript">
      window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["identify","track"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("1162175837");
    </script>
  </head>

  <body>

        <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top" role="navigation" data-ng-controller="NavBarController">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="/#/users/<%=@user.id%>">
             <img src="https://s3.amazonaws.com/roundview4/static_assets/Roundview_logo_full.svg" alt="Roundview Logo" class="navbar-logo">
            </a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
               <li> <a href="/#/users/<%=@user.id%>"> My Profile </a></li> 
               <li> <a href="/#/discover"> Discover </a> </li>
               <li> <a href="/#/connect_accounts"> Connect APIs </a></li> 
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li> <%= mail_to "contact@roundview.co", "Contact Us", :target => '_blank' %> </li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
            </ul>
            <!-- <div class="navbar-form navbar-right pull-right"> -->
              
            <!-- </div> -->
              <!-- <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">About</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li> -->
            
          </div><!--/.nav-collapse -->
        </div>
      </div>  

    <!-- Begin page content -->
    
    <div class="container">
    	<%= yield %>
    </div>

    
    
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
  <%= render 'layouts/footer' %>
   <script>
    if (document.location.hostname.search("roundview.co") !== -1) {
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-46327528-2', 'auto');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
    }
  </script>
</html>